version: '3.4'

services:
  networkmonitor:
    image: networkmonitor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
  webpinger:
    image: webpinger
    build:
      context: .
      dockerfile: WebPinger/Dockerfile
    ports:
      - 5000:80
      - 443